export const ClientesTypes = {
    CHANGE_INPUT: "CHANGE_INPUT",
    CREAR_CLIENTE: "CREAR_CLIENTE",
    ELIMINAR_CLIENTE: "ELIMINAR_CLIENTE",
    EDITAR_CLIENTE: "EDITAR_CLIENTE",
    OBTENER_DATOS_CLIENTE: "OBTENER_DATOS_CLIENTE",
    OBTENER_ID_CLIENTE: "OBTENER_ID_CLIENTE"
}