export const EmpleadosTypes = {
    CHANGE_INPUT: "CHANGE_INPUT",
    CREAR_EMPLEADO: "CREAR_EMPLEADO",
    ELIMINAR_EMPLEADO: "ELIMINAR_EMPLEADO",
    EDITAR_EMPLEADO: "EDITAR_EMPLEADO",
    OBTENER_DATOS_EMPLEADO: "OBTENER_DATOS_EMPLEADO",
    OBTENER_ID_EMPLEADO: "OBTENER_ID_EMPLEADO"
}