export const ProductosTypes = {
    CHANGE_INPUT: "CHANGE_INPUT",
    CREAR_PRODUCTO: "CREAR_PRODUCTO",
    ELIMINAR_PRODUCTO: "ELIMINAR_PRODUCTO",
    EDITAR_PRODUCTO: "EDITAR_PRODUCTO",
    OBTENER_DATOS_PRODUCTO: "OBTENER_DATOS_PRODUCTO",
    OBTENER_ID_PRODUCTO: "OBTENER_ID_PRODUCTO"
}
