export const VentasTypes = {
    CHANGE_INPUT: "CHANGE_INPUT",
    CREAR_VENTAS: "CREAR_VENTAS",
    ELIMINAR_VENTAS: "ELIMINAR_VENTAS",
    EDITAR_VENTAS: "EDITAR_VENTAS",
    OBTENER_DATOS_VENTAS: "OBTENER_DATOS_VENTAS",
    OBTENER_ID_VENTAS: "OBTENER_ID_VENTAS"
}